### ISSUE TITLE
Not working with Framer3

### ISSUE THREAD

**Issue by florianpeninon** [tisho/framer-animation-controls#1]
I first got a warning from Framer which is ok :
`Utils.setDefaultProperties: got unexpected option: 'aid -> cardAwayRight'`
But after I got an error :
`Uncaught TypeError: Cannot read property 'concat' of undefined framer-animation-controls.js:4`

**Comment by tisho** [comment]
Yeah, I haven't looked into compatibility with Framer 3, yet. Should be coming in shortly, though :) Thanks for reporting this.

**Comment by tisho** [comment]
I added basic Framer 3 compatibility today. Since the animation internals were rewritten, I actually want to do a more significant rewrite of the controls, but this should tide you over.
